apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  destination:
    namespace: homelab
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:ASalad42/homelab-k8.git
    targetRevision: main
    path: apps/k8s-manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
