apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30 
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          volumeMounts:
            - mountPath: /srv
              name: arr-data
            - mountPath: /database
              name: filebrowser-db
            - mountPath: /config
              name: filebrowser-config
      volumes:
        - name: arr-data
          persistentVolumeClaim:
            claimName: arr-data-pvc
        - name: filebrowser-db
          persistentVolumeClaim:
            claimName: filebrowser-db-pvc
        - name: filebrowser-config
          persistentVolumeClaim:
            claimName: filebrowser-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: homelab
spec:
  type: ClusterIP
  selector:
    app: filebrowser
  ports:
    - name: webui
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filebrowser-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: filebrowser.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filebrowser
                port:
                  number: 80