apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        hardware: gpu # Ensures Jellyfin pod is scheduled on node with GPU passthrough
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 8920
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: UMASK
            value: "022"
          - name: TZ
            value: "Europe/London"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet: 
              path: /
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 30 
          readinessProbe:
            httpGet:
              path: /
              port: 8096
            initialDelaySeconds: 30
            periodSeconds: 15
          volumeMounts:
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /data
              name: arr-data
            - mountPath: /transcode
              name: jellyfin-transcode
          securityContext: 
            privileged: true 
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: arr-data
          persistentVolumeClaim:
            claimName: arr-data-pvc
        - name: jellyfin-transcode
          emptyDir: {}
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: homelab
spec:
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
    - name: webui-http
      port: 8096
      targetPort: 8096
      protocol: TCP
    - name: webui-https
      port: 8920
      targetPort: 8920
      protocol: TCP
    - name: dlna-discovery
      port: 7359
      targetPort: 7359
      protocol: UDP
    - name: upnp
      port: 1900
      targetPort: 1900
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: jellyfin.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
    - http:
        paths:
          - path: /jellyfin
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096