apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-data-pvc
  namespace: homelab
spec:
  storageClassName: nfs-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
